In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(digits.data,digits.target,test_size = 0.3)

In [3]:
lr = LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

C:\Users\avraj\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [4]:
svm = SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9851851851851852

In [5]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9555555555555556

In [6]:
# The problem is if we run manytimes train_test_split the accuracy of the models are getting changed so we need find a solution .

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [18]:
def get_score(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [19]:
get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test)

C:\Users\avraj\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9215358931552587

In [20]:
get_score(SVC(),X_train,X_test,Y_train,Y_test)

0.9649415692821369

In [21]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [27]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train,X_test,Y_train,Y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,Y_train,Y_test))
                                    

C:\Users\avraj\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\avraj\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/mod

In [28]:
scores_l

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [29]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [30]:
scores_rf

[0.9282136894824707, 0.9515859766277128, 0.9198664440734557]

In [31]:
# Insted of doingf all this stuff we can do this -- >
from sklearn.model_selection import cross_val_score

In [32]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\avraj\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\avraj\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/mod

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [33]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [35]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93055556, 0.89444444, 0.96100279, 0.9637883 , 0.90529248])

In [36]:
cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target)

array([0.925     , 0.90833333, 0.94986072, 0.94707521, 0.90529248])

In [37]:
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target)#tuning the estimeters here its called "parameter tuning".

array([0.93055556, 0.88333333, 0.9637883 , 0.96657382, 0.92200557])